# The final, definitive configuration for Netlify

# This section tells Netlify how to build your React frontend
[build]
  # 1. First, tell Netlify that all frontend commands run from this folder:
  base    = "frontend"
  # 2. Inside that 'base' folder, run this command to install and build:
  command = "npm install && npm run build"
  # 3. The final website files will be in the 'build' folder (relative to 'base'):
  publish = "build"

# This section tells Netlify where to find your serverless functions
[functions]
  # The single '/' at the beginning tells Netlify to look for this folder
  # at the absolute root of the project, ignoring the 'base' directory.
  directory = "/netlify/functions"