# The final and correct Netlify configuration for a monorepo

# This section tells Netlify how to build your React frontend
[build]
  # 1. First, tell Netlify that all frontend commands run from this folder:
  base    = "frontend"
  # 2. Inside that 'base' folder, run this command to install and build:
  command = "npm install && npm run build"
  # 3. The final website files will be in the 'build' folder (relative to 'base'):
  publish = "build"

# This section tells Netlify where to find your serverless functions
# This path is always relative to the root of your project.
[functions]
  directory = "netlify/functions"